### ISSUE TITLE
Some errors.

### ISSUE THREAD

**Issue by chaochen99** [Glaciohound/LM-Infinite#6]
Hi, 

when I run the code, I encounter two errors:

**1. An error 1 occurred when running Evaluation on Passkey Retrieval Task:**
_Traceback (most recent call last):
  File "scripts/eval_downstream_tasks.py", line 121, in <module>
    main(args)
  File "scripts/eval_downstream_tasks.py", line 71, in main
    output, output_ids = model.generate(
TypeError: generate() missing 1 required positional argument: 'do_sample'_
**2. An error 2 occurred when running Generation":**
_Traceback (most recent call last):
  File "scripts/eval_generation.py", line 107, in <module>
    main(args)
  File "scripts/eval_generation.py", line 94, in main
    scores = generation_overall_metric(
  File "LM-Infinite/data/generation_metrics.py", line 6, in generation_overall_metric
    rouge = evaluate.load("rouge")
  File "python3.8/dist-packages/evaluate/loading.py", line 731, in load
    evaluation_module = evaluation_module_factory(
  File "python3.8/dist-packages/evaluate/loading.py", line 681, in evaluation_module_factory
    raise FileNotFoundError(
FileNotFoundError: Couldn't find a module script at LM-Infinite/rouge/rouge.py. Module 'rouge' doesn't exist on the Hugging Face Hub either._

Looking forward to your reply！

**Comment by Glaciohound** [comment]
Hello. Thanks for your interests in our work!

The first error results from an argument mismatch in API calls, which is fixed in the current comment.

The second error is likely due to `rouge-score` not installed, and you can `pip install` it. More information can be found in https://github.com/huggingface/evaluate/issues/323.
